project_name: 'data_checker'
lengths:
  obs_len: 4
  pred_len: 8
  act_len: 8
dims:
  obs_dim: 13
  action_dim: 7
data:
  path: './diffusion_data_xarm.npy'
  batch_size: 16
  num_workers: 1
  shuffle: True
  persistent_workers: True
diffusion:
  num_diffusion_iters: 100
  beta_schedule: 'squaredcos_cap_v2'
  clip_sample: True
  prediction_type: 'epsilon'
training:
  num_epochs: 100
  ema_power: 0.75
  lr: 1e-4
  weight_decay: 1e-6
  lr_scheduler: 'cosine'
  num_warmup_steps: 500