project_name: "data_checker"

lengths:
  obs_len: 2
  pred_len: 16
  act_len: 8

openness_threshold: 6 # [cm]

dims:
  obs_dim: 12
  action_dim: 6

data:
  path: "/haozhe-pv/diffusion/data_xarm-2-16-8.npy"
  train_set_ratio: 0.9
  batch_size: 16
  num_workers: 1
  shuffle: True
  persistent_workers: True

diffusion:
  num_diffusion_iters: 100
  beta_schedule: "squaredcos_cap_v2"
  clip_sample: True
  prediction_type: "epsilon"

training:
  num_epochs: 100
  ema_power: 0.75
  lr: 1e-4
  weight_decay: 1e-6
  lr_scheduler: "cosine"
  num_warmup_steps: 500
